export const LoginPageLocators = {
  HomePageSignUporLoginButton: 'a[href="/login"]',
  LoginPageName: "input[placeholder='Name']",
  LoginPageEmailAddress: "div.signup-form input[placeholder='Email Address']",
  LoginPageSignUpBtn: "button[data-qa='signup-button']",
  LoginPageTitleMr: "label[for='id_gender1']",
  LoginPageTitleMrs: "label[for='id_gender2']",
  LoginPagePassword: '#password',
  LoginPageDayOfBirth: '#days',
  LoginPageMonthOfBirth: '#months',
  LoginPageYearOfBirth: '#years',
  LoginPageFirstName: '#first_name',
  LoginPageLastName: '#last_name',
  LoginPageCompany: '#company',
  LoginPageAddress1: '#address1',
  LoginPageAddress2: '#address2',
  LoginPageCountry: '#country',
  LoginPageState: '#state',
  LoginPageCity: '#city',
  LoginPageZipCode: '#zipcode',
  LoginPageMobileNumber: '#mobile_number',
  LoginPageCreateAccountText: 'Create Account',
  LoginPageAccountCreatedText: 'h2.title.text-center > b',
  LoginPageAccountCongratsMessage: '#form div.container p:first-of-type',
  LoginPageAccountAdditionalInfo: '#form div.container p:last-of-type',
  LoginPageContinueBtn: 'a.btn.btn-primary',
  LoginAccountEmailAddress: "input[data-qa='login-email']",
  LoginAccountPassword: "input[name='password']",
  LoginAccountLoginBtn: "button[data-qa='login-button']",
  LoginPageLogOutBtn: "a[href='/logout']",
  LoginPageDeleteAccountBtn: "a[href='/delete_account']"
};
