name: Cucumber Playwright Tests

on:
  workflow_dispatch:
    inputs:
      browser:
        description: 'Choose the browser'
        required: true
        default: 'chromium'
        type: choice
        options:
          - chromium
          - firefox
          - webkit
      tag:
        description: 'Tag to run (e.g. @smoke, @regression, @sanity)'
        required: false
        type: choice
        options:
          - '@smoke'
          - '@regression'
          - '@sanity'
          - '@sample'
      feature:
        description: 'Feature file path (e.g. features/login.feature)'
        required: false
        default: 'src/features'
      baseURL:
        description: 'Base URL to test against'
        required: true
        default: 'https://automationteststore.com'
      scenario:
        description: 'Scenario title (e.g. Validate successful login)'
        required: false

jobs:
  extract-tags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Extract Cucumber tags
        id: extract-tags
        run: |
          node scripts/extract-cucumber-tags.cjs
          TAGS=$(jq -c '.tags' cucumber-tags.json)
          echo "tags=$TAGS" >> $GITHUB_OUTPUT

  run-cucumber-playwright:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: ${{ fromJson(needs.extract-tags.outputs.tags) }}
    needs: extract-tags
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Run scenarios
        run: |
          echo "BROWSER: ${{ github.event.inputs.browser }}"
          echo "TAG: ${{ matrix.tag }}"
          echo "FEATURE: ${{ github.event.inputs.feature }}"
          echo "SCENARIO: ${{ github.event.inputs.scenario }}"
          echo "BASE_URL: ${{ github.event.inputs.baseURL }}"

          export BROWSER=${{ github.event.inputs.browser }}
          export BASE_URL=${{ github.event.inputs.baseURL }}

          CMD="npx cucumber-js ${{ github.event.inputs.feature }} --exit"

          if [ -n "${{ matrix.tag }}" ]; then
            CMD="$CMD --tags '${{ matrix.tag }}'"
          fi

          if [ -n "${{ github.event.inputs.scenario }}" ]; then
            CMD="$CMD --name '${{ github.event.inputs.scenario }}'"
          fi

          echo "Running command: $CMD"
          eval $CMD

      - name: List allure-results contents
        run: ls -l allure-results || echo "allure-results folder does not exist"

      - name: Generate Allure report
        run: |
          npm install -g allure-commandline --no-save
          allure generate allure-results --clean -o allure-report

      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: ./allure-report

      - name: Upload HTML Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: html-report
          path: ./reports
